name: NextLib
version: '${version}'
main: io.github.chi2l3s.nextlib.NextLib
api-version: '1.16'
softdepend: ["PlaceholderAPI"]
libraries:
  - com.tchristofferson:ConfigUpdater:2.2
  - com.zaxxer:HikariCP:7.0.2
